import fs from 'node:fs'
import path from 'node:path'

const lucideDir = path.resolve('node_modules/lucide-react/dist/esm/icons')
const iconFiles = fs.readdirSync(lucideDir).filter(f => f.endsWith('.js') && !f.endsWith('.map'))

const icons = []
for (const file of iconFiles) {
  const name = file.replace(/\.js$/, '')
  const content = fs.readFileSync(path.join(lucideDir, file), 'utf8')
  // skip alias files that just re-export another icon
  if (content.match(/export \{ default \} from '\.\/[^']+\.js'/)) continue
  icons.push(name)
}

icons.sort()

// Keyword extraction: use the name segments as keywords
const entries = icons.map(name => {
  const keywords = name.split('-')
  return `  { id: ${JSON.stringify(name)}, keywords: ${JSON.stringify(keywords)} }`
})

const output = `// Auto-generated by scripts/generate-icons.mjs — do not edit manually
// Run: pnpm gen:icons

export interface IconMeta {
  id: string
  keywords: string[]
}

export const ICONS: readonly IconMeta[] = [
${entries.join(',\n')}
] as const

export const ICON_COUNT = ${icons.length}
`

fs.mkdirSync('lib', { recursive: true })
fs.writeFileSync('lib/icons.ts', output)
console.log(`Generated lib/icons.ts with ${icons.length} unique icons`)
